"""create payments table

Revision ID: 1982efd56004
Revises: 
Create Date: 2026-03-03 15:16:00.585517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1982efd56004'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_reference', sa.String(length=60), nullable=False),
    sa.Column('order_tracking_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('status_description', sa.String(length=255), nullable=True),
    sa.Column('confirmation_code', sa.String(length=100), nullable=True),
    sa.Column('payment_account', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_merchant_reference'), 'payments', ['merchant_reference'], unique=True)
    op.create_index(op.f('ix_payments_order_tracking_id'), 'payments', ['order_tracking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_order_tracking_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_merchant_reference'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
